# Generated by Django 6.0.3 on 2026-03-22 12:48

import django_nh3.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=django_nh3.models.Nh3TextField(verbose_name='Content'),
        ),
    ]
